### ISSUE TITLE
Crates that droped from bus usually doesnt droping items 

### ISSUE THREAD

**Issue by gaejuck** [Mikusch/fortress-royale#30] opened 2021-01-04 08:29 UTC
can solves this problem?

**Comment by gaejuck** [comment] 2021-01-04 08:35
also I configurated loot table

**Comment by Mikusch** [comment] 2021-01-04 08:46
It's a SourceMod bug, fixed in 1.11

Duplicate of #11

**Closed by Mikusch** 2021-01-04 08:46 UTC
Labels: bug, duplicate

**Comment by gaejuck** [comment] 2021-01-04 08:50
thx
